(global-set-key (kbd "C-n") 'tab-bar-new-tab)
(global-set-key (kbd "C-q") 'tab-bar-close-tab)
(global-set-key (kbd "C-t") 'treemacs)
(global-set-key (kbd "C-A") 'treemacs-add-project-to-workspace)
(global-set-key (kbd "C-D") 'treemacs-remove-project-from-workspace)
(global-set-key (kbd "C-z") 'undo)
(global-set-key (kbd "C-c C-p") 'my/treemacs-set-root-to-project)
(global-set-key (kbd "C-c C-a") 'my/treemacs-add-project)
(global-set-key (kbd "C-c C-r") 'my/treemacs-remove-project)
